# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e7b5881d699b9a2b07d00e2106755bb7aa2d42465210161e4183c70bffb024db2e6135ea595569e9c598155b5c69d37779808e59a2fa7803a58b0f2ac37060e

test:
  secret_key_base: 79a6d349a28c2691b0c0a5823a2a8e74c1db40a7aca0cae0ae6ba713e4ade6c4c5d1edb6fe975cbfce70ac6afd2a4059bde9d595c918be2189f3913fa9ba6d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
